### ISSUE TITLE
Wrong token ranges when sentences are in vertical input

### ISSUE THREAD

**Issue by matyaskopp** [ufal/nametag#11]
Nametag gives wrong result for vertical input and output when sentences are split with new line

left:  **No double** endlines at input
right: double endlines split sentences
![image](https://user-images.githubusercontent.com/5867995/101186250-21ab6c00-3653-11eb-8f04-e40f15d3c48d.png)

It seems that overflow happen every thousand tokens:
10-times bigger input:
![image](https://user-images.githubusercontent.com/5867995/101187367-8fa46300-3654-11eb-94f9-3727d94e30c2.png)

**Comment by foxik** [comment]
Adding also @strakova

**Comment by foxik** [comment]
Thanks for reporting! I can see that we are resetting the numbers in vertical output format; we will fix it.

But I was unable to replicate the problem with double newlines -- could you please send the inputs you used, and the expected outputs? Thanks.

**Comment by foxik** [comment]
A fix has just been deployed. If you encounter any problems, please report here.

Thanks for making NameTag better :-)
