### ISSUE TITLE
Unexpected category in czech-cnec2.0-200831 model

### ISSUE THREAD

**Issue by matyaskopp** [ufal/nametag#13]
For this sentence:
```
Dobrý den, dámy a pánové, já bych si dovolil ještě navrhnout jednu změnu v pevném zařazení, a to konkrétně v bodu 68, sněmovní tisk 51, Výroční zprávy a účetní závěrky zdravotních pojišťoven za rok 2012, a to na pátek 14. 2. po bloku třetích čtení.
```
nametag returns unexpected category **C - Bibliography container**, this category is not defined in https://ufal.mff.cuni.cz/~strakova/cnec2.0/ne-type-hierarchy.pdf

![image](https://user-images.githubusercontent.com/5867995/109392965-83603700-791f-11eb-94dc-115519096356.png)

**Comment by foxik** [comment]
The referenced image describes only the entity types; apart from them, the hierarchy also includes _container NEs_, described in Chapter 2 of the technical report [Ševčíková et al., 2007](https://ufal.mff.cuni.cz/~zabokrtsky/publications/papers/tsd07-namedent.pdf) referenced in CNEC 1/CNEC 2 description.

The container NEs are:
- `P` for  (complex) person names,
- `T` for temporal expressions,
- `A` for addresses,
- `C` for bibliographic items

I agree the documentation on the web could mention them directly instead of referencing the report.

**Comment by matyaskopp** [comment]
Missing container types in the description is confusing. And "super-types" that are distinguished from container with capital letter too...

So if you can please rephrase this sentence: _The corpus uses 46 named entity types, which can be nested._ (https://ufal.mff.cuni.cz/nametag/2/models)
Yes, it means that CNEC contains exactly 46 types that can be nested - it is true. It does not exclude the possibility of other types. But careless reader (me) expects that the sentence covers all possible entities.

**Comment by stranak** [comment]
I agree it would be better to clarify the model description:
> The corpus uses 46 named entity types, which can be nested.

#### I would change it into something like this (using and modifying the paper in references):
The corpus uses 46 atomic named entity types, which can be embedded, e.g., the river name can be part of a name of a city as in `<gu =Ústí nad <gh Labem>>`). There are also  4 so-called contaner NEs: two or more NEs are parts of a container NE (e.g., two NEs, a first name and a surname, form together a person name container NE such as in <P<pf Paul> <ps Newman>>). The 4 container NEs are marked with a capital one-letter tag: `P` for (complex) person names, `T` for temporal expressions, `A` for addresses, and `C` for bibliographic items.

**Comment by strakova** [comment]
Thanks for your suggestions and sorry for the confusion. I explained the existence of the NE containers in both CNEC and NameTag2 documentations.
