### ISSUE TITLE
Integrate with CLARIN LR Switchboard

### ISSUE THREAD

**Issue by stranak** [ufal/nametag#18]
#### Integrate NameTag in https://switchboard.clarin.eu similarily to how UDPipe has been integrated.

-----Original message-----
From: Ondrej Kosarko

>mam jeste dotaz k nametagu. Potrebovali bychom ho pridat do switchboardu. 
>Switchboard uplne nepouziva rest api, ale udela redirect s predvyplnenejma parametrama. Enduser je clovek ne stroj, takze >dostane nejakou vizualizaci. 
>V udpipe funguje napr [ https://lindat.mff.cuni.cz/services/udpipe/?data=Test+sentence&model=eng | >https://lindat.mff.cuni.cz/services/udpipe/?data=Test+sentence&model=eng ] + myslim ze data muze byt i url souboru s >textem. 

>Je neco takoveho i v nametagu? Jak dlouho by to pripadne zabralo pretahnout z toho udpipe kodu?
>Mimochodem jde vubec v nametagu vybrat model iso kodem jazyka?

v Nametagu nic takového zatím není. Tu podporu psal ve skutečnosti Josef,
je to v https://github.com/ufal/udpipe/blob/master/web/lindat-service/fill-using-params.js
a https://github.com/ufal/udpipe/blob/master/web/lindat-service/run.php#L262-L281 .
Přetáhnout to do NameTagu by měla být relativně přímočará záležitost
(copy-paste, zkusit, a případně malinko pošťouchat, kdyby to z nějakého
důvodu nefungovalo).

A ano, model vybrat iso kódem jazyka (naštěstí) jde.

**Comment by EbrithilNogare** [comment]
Aplikace switchboard.clarin.eu  mi pripada jako zbuildena React aplikace,
presne to nevim, protoze jsem nenasel zdrojaky.

Jeslti je to opravdu React, budou poterba originalni zdrojaky, nebo alespon ta cast zajistujici submitujici stranku.
Zde se bude muset odchytavat ktera zalozka se ma zobrazit a pak prislusne pole vyplnit.

pozn. pro me, abych pak vedel co hledat
```
state.active = [0,1,2]
state.link = "xyz"
state.text = "xyz"
```

**Comment by stranak** [comment]
Teď si asi nerozumíme. Na Switchboard vůbec sahat nebudete. Víceméně vše o tom, jak funguje, by mělo být k nalezení zde: https://github.com/clarin-eric/switchboard Jak zdrojáky, tak dokumentace, tak články (doporučuju ten v CL).

Jde tedy o to, aby se do nametagu pridala podpora pro predavani parametru, jak si ho predstavuje Switchboard. https://github.com/clarin-eric/switchboard-tool-registry

A presne toto uz drive kolegove udelali pro UDPipe, cili musite kouknout tam, jak to udelali, a prevzit to pro NameTag, jak popisuje @kosarko vyse, vc. kodu, o ktery jde.

**Comment by kosarko** [comment]
Switchboard od nas dostane jenom definici sluzby v jsonu a to jako pull request (treba v https://github.com/clarin-eric/switchboard-tool-registry/pull/45 se pridaval preklad, nebo v https://github.com/clarin-eric/switchboard-tool-registry/pull/62 se pridavaly dalsi jazyky do udpipe) 

Pro nejaky demo napr zkusit nahrat nejakej ceskej text do
https://switchboard.clarin.eu/input
a pak vybrat treba ten udpipe pro analyzu. A koukat "kudy" se ten vstupni text predvyplni v udpipe.

Na strane Nametagu by to pak melo fungovat obdobne (ne-li uplne stejne).

json a ten pull request potom kdyztak doladime hromadneji, az to bude v tom rozhrani nametagu hotove

**Comment by EbrithilNogare** [comment]
Dobra, uz asi chapu o cem je rec, ale potreboval bych tedy jeste pristup k zdrojakum webu NameTagu.
UDPipe ma v rootu gitu slozku web, ze ktere tedy lindati web cerpa html/php a ve ktere uvadena zmena byla provedena.
Protoze v repozitari [NameTag git](https://github.com/ufal/nametag) to neni a nevim, kde se zdrojaky pro /services/ nachazeji.

**Comment by kosarko** [comment]
@foxik 
> Dobra, uz asi chapu o cem je rec, ale potreboval bych tedy jeste pristup k zdrojakum webu NameTagu.
> UDPipe ma v rootu gitu slozku web, ze ktere tedy lindati web cerpa html/php a ve ktere uvadena zmena byla provedena.
> Protoze v repozitari [NameTag git](https://github.com/ufal/nametag) to neni a nevim, kde se zdrojaky pro /services/ nachazeji.

**Comment by foxik** [comment]
Spíš z historických důvodů mají všechny služby kromě UDPipe tyhle části soukromé (tak jako tak musíme mít soukromou repository kvůli tomu, že pracujeme nad daty s někdy neveřejnou licencí, a přišlo mi, že to, co není užitečné ostatním, v té veřejné repo být nemusí; s UDPipe žádnou neveřejnou repo nemáme, tak jsem to plácnul rovnou do té veřejné).

Každopádně jsem to fill-using-params portnul z UDPipe a nasadil, takže parametry "model" (přesný model nebo nějaký ISO kód jazyka) a "data" (text nebo URL, které ale musí mít nastavený CORS, protože se to stahuje javascriptem) fungují.

**Comment by kosarko** [comment]
PR do switchboardu clarin-eric/switchboard-tool-registry#123
