### ISSUE TITLE
Nametag REST server fails when compiled in debug mode

### ISSUE THREAD

**Issue by curusarn** [ufal/nametag#2]
### Reproduce the bug:

1. Change compilation mode to debug: Edit line 81 in `Makefile.builtem` from: `  MODE=normal` to `  MODE=debug`

2. Recompile the server: run `make server`

3. Run the server

4. Send any `recognize` request to server `URL:PORT/recognize?data=whatever`

### Output:
```
Successfully started nametag_server on port 8080.
/usr/include/c++/4.9/debug/vector:357:error: attempt to subscript container 
    with out-of-bounds index 0, but container only holds 0 elements.

Objects involved in the operation:
sequence "this" @ 0x0x7f76200091b0 {
  type = NSt7__debug6vectorINS0_IjSaIjEEESaIS2_EEE;
}
Aborted
```

Best regards,

Simon Let

**Comment by foxik** [comment]
Thanks for a very good bug-report, fixed.
