### ISSUE TITLE
Support Tensorflow 2.x and Python 3.8+ in NameTag 2

### ISSUE THREAD

**Issue by PROrock** [ufal/nametag#22]
Hi, this is not an urgent feature request, but sooner or later, it would be great to see this done.

As NameTag 2 is using Tensorflow 1.x, it needs Python 3.7 (or older). But since Python 3.7 will reach its end of life soon (27 Jun 2023 according to https://endoflife.date/python ) and since it blocks using newer Python versions, it would be awesome if someone could migrate the code from TF 1.x. to 2.x. There is even an official migration manual on TF pages: https://www.tensorflow.org/guide/migrate .
Another solution would be to release NameTag 3 written in TF 2.x (or other language).

**Comment by foxik** [comment]
Hi,

yes, something definitely need to be done.

NameTag3 will be part of LinPipe https://github.com/ufal/linpipe, but I would expect a release at the end of 2023.

In the meantime, we can still use the `nvidia-tensorflow`, which is Nvidia-maintained fork of TensorFlow 1.15, working with Python 3.8 (and also newer CUDA, in case you have too new GPUs) -- that should cover the area before we have NameTag 3 working in LinPipe.

**Comment by PROrock** [comment]
Ok, thanks, foxik, for a quick response and good luck with linpipe :-)
