### ISSUE TITLE
std::iterator deprecated in C++17

### ISSUE THREAD

**Issue by jwijffels** [ufal/nametag#24]
The R package [nametagger ](https://cran.r-project.org/web/packages/nametagger/index.html) wraps the nametag C++ library. 
The default on R is now to compile using C++17 instead of C++11.
As std::iterator is deprecated in C++17, would it be possible to update the library such that it can be compiled without C++17 warnings. 

```
Found the following significant warnings:
  ./nametag/src/unilib/utf8.h:148:52: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  ./nametag/src/unilib/utf8.h:180:52: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  nametag/src/unilib/utf16.h:116:53: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  nametag/src/unilib/utf16.h:148:53: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  nametag/src/unilib/utf8.h:148:52: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  nametag/src/unilib/utf8.h:180:52: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
```

**Comment by foxik** [comment]
We generally do not guarantee warning-free compilation with different C++ standard (and some parts of our infrastructure requires C++11, given that this is legacy software at this point), but this one was easy. (I am not sure why the C++ committee passed https://cplusplus.github.io/LWG/issue2438 in the first place.) Fixed in https://github.com/ufal/unilib/commit/d00b2b3ab77bf9f4a92be466112854370ec0c833 and 2aa1d1de78d.

**Comment by jwijffels** [comment]
Many thanks for the quick fix and your time. I've uploaded the R wrapper to CRAN yesterday and incorporated these fixes.
