### ISSUE TITLE
Server returns invalid json when there is no data.

### ISSUE THREAD

**Issue by curusarn** [ufal/nametag#8]
*This is different bug than #6*

These two calls give me Invalid JSON:
`>>> curl "localhost:8000/recognize?data="`
`>>> curl "localhost:8000/recognize?output=vertical&data="`
```
{
 "model": "cnec2.ner",
 "acknowledgements": [
  "http://ufal.mff.cuni.cz/nametag#nametag_acknowledgements",
  "http://ufal.mff.cuni.cz/morphodita#morphodita_acknowledgements"
 ],
 "result": }
```

Feel free to contact me to get more information.

**Comment by foxik** [comment]
Sorry, I found out about the issue only now. Anyway, it seem to have been fixed already.
